---
version: 2.1

orbs:
  op: twdps/onepassword@dev:<<pipeline.git.revision>>

globals:
  - &context orb-publishing

commands:

  echo-message:
    parameters:
      msg:
        type: string
    steps:
      - run:
          name: echo msg
          command: echo "<< parameters.msg >>"

jobs:

  test install on alpine executor:
    docker:
      - image: twdps/circleci-remote-docker:alpine-stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install test dependencies
          command: |
            apk add --no-cache sudo bash wget curl
      - op/packages:
          os: Alpine
          op-version: 2.24.0-r1
          opw-version: 0.1.0
      - run:
          name: confirm installed version for available packages
          command: |
            set -exo pipefail
            op --version | grep "2.24.0"
            opw version | grep "0.1.0"


  test install on ubuntu machine executor:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - checkout
      - op/packages:
          op-version: 2.24.0-1
          opw-version: 0.1.0
      - run:
          name: confirm installed version for available packages
          command: |
            set -exo pipefail
            op --version | grep "2.24.0"
            opw version | grep "0.1.0"

  test op env:
    docker:
      - image: twdps/circleci-base-image:alpine-stable
    steps:
      - checkout
      - setup_remote_docker
      - op/env
      - run:
          name: test op env
          command: |
            set -exo pipefail
            echo $GMAIL_ADDRESS | grep "twdps"

workflows:

  integration tests:
    jobs:
      - test install on alpine executor
      - test install on ubuntu machine executor
